import type { DatabaseShape } from "./types";

const now = new Date().toISOString();

export const seedDatabase: DatabaseShape = {
  businesses: [
    {
      id: "b-1",
      name: "Sai Electricals",
      category: "Electrical Contractor",
      tagline: "24x7 electrician support for homes, shops, and offices.",
      description:
        "Sai Electricals provides wiring setup, MCB repair, inverter installation, and electrical safety inspections for homes and commercial properties. The team focuses on quick response, transparent pricing, and same-day service in core Pune localities.",
      locality: "Kothrud",
      city: "Pune",
      addressLine1: "Shop 4, Shree Residency, Paud Road",
      pincode: "411038",
      ownerName: "Sachin Kulkarni",
      establishedYear: 2014,
      email: "support@saielectricals.in",
      website: "https://saielectricals.in",
      rating: 4.7,
      reviewCount: 142,
      isOpenNow: true,
      verified: true,
      phone: "+919876543210",
      whatsappNumber: "+919876543210",
      serviceAreas: ["Kothrud", "Karve Nagar", "Erandwane", "Baner", "Aundh"],
      languages: ["English", "Hindi", "Marathi"],
      keywords: [
        "electrician near me",
        "emergency electrician pune",
        "mcb repair",
        "inverter wiring",
        "house rewiring",
        "electrical contractor kothrud",
        "ceiling fan installation",
        "switchboard replacement",
        "3 phase connection work",
      ],
      highlights: [
        "30-minute emergency response",
        "GST invoice available",
        "Certified technicians",
        "Transparent pricing",
      ],
      services: [
        {
          name: "Home Wiring and Rewiring",
          priceLabel: "Starts Rs 499",
          description:
            "Complete rewiring for homes, flats, and offices with safety checks.",
        },
        {
          name: "MCB and Distribution Board Repair",
          priceLabel: "Starts Rs 299",
          description:
            "Fault isolation, MCB replacement, load balancing, and DB maintenance.",
        },
        {
          name: "Inverter and UPS Installation",
          priceLabel: "Starts Rs 799",
          description:
            "Installation, wiring, and troubleshooting for backup power systems.",
        },
      ],
      businessHours: [
        { day: "Monday", open: "09:00", close: "20:00", closed: false },
        { day: "Tuesday", open: "09:00", close: "20:00", closed: false },
        { day: "Wednesday", open: "09:00", close: "20:00", closed: false },
        { day: "Thursday", open: "09:00", close: "20:00", closed: false },
        { day: "Friday", open: "09:00", close: "20:00", closed: false },
        { day: "Saturday", open: "09:00", close: "18:00", closed: false },
        { day: "Sunday", closed: true },
      ],
      media: {
        logo: "/showcase/business-electrical.svg",
        coverImages: ["/showcase/business-electrical.svg"],
        gallery: [
          "/showcase/business-electrical.svg",
          "/showcase/service-home.svg",
          "/showcase/offer-growth.svg",
        ],
      },
      faqs: [
        {
          question: "Do you provide emergency electrical support?",
          answer:
            "Yes, emergency visits are available in Pune service areas depending on technician availability.",
        },
        {
          question: "Do you provide GST invoices?",
          answer: "Yes, GST invoices are provided for all paid service jobs.",
        },
      ],
      policies: {
        paymentMethods: ["UPI", "Cash", "Card", "Bank Transfer"],
        homeService: true,
        emergencyService: true,
        appointmentRequired: false,
        cancellationPolicy:
          "No cancellation fee if cancelled at least 1 hour before technician dispatch.",
      },
      socialLinks: {
        instagram: "https://instagram.com/saielectricalspune",
        facebook: "https://facebook.com/saielectricalspune",
      },
      verification: {
        gstNumber: "27ABCDE1234F1Z5",
        licenseNumber: "ELEC-PN-2014-1172",
        verifiedOn: now,
      },
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "b-2",
      name: "Urban Steel Works",
      category: "Fabrication and Welding",
      locality: "MIDC",
      city: "Nashik",
      rating: 4.6,
      reviewCount: 88,
      isOpenNow: true,
      verified: true,
      phone: "+919912345670",
      whatsappNumber: "+919912345670",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "b-3",
      name: "Arogya Diagnostics",
      category: "Diagnostic Center",
      locality: "Shivaji Nagar",
      city: "Nagpur",
      rating: 4.8,
      reviewCount: 214,
      isOpenNow: false,
      verified: false,
      phone: "+918889990011",
      whatsappNumber: "+918889990011",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "s-1",
      name: "Shivam Packers and Movers",
      category: "Logistics",
      locality: "Andheri East",
      city: "Mumbai",
      rating: 4.5,
      reviewCount: 311,
      isOpenNow: true,
      verified: true,
      phone: "+917718882233",
      whatsappNumber: "+917718882233",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "s-2",
      name: "A1 Dental Clinic",
      category: "Healthcare",
      locality: "Bodakdev",
      city: "Ahmedabad",
      rating: 4.8,
      reviewCount: 169,
      isOpenNow: true,
      verified: true,
      phone: "+919098883322",
      whatsappNumber: "+919098883322",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "s-3",
      name: "Morya Paint House",
      category: "Hardware Store",
      locality: "Satara Road",
      city: "Pune",
      rating: 4.3,
      reviewCount: 92,
      isOpenNow: false,
      verified: false,
      phone: "+919766551122",
      whatsappNumber: "+919766551122",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "s-4",
      name: "Royal Air Cool Services",
      category: "AC Repair",
      locality: "Mansarovar",
      city: "Jaipur",
      rating: 4.6,
      reviewCount: 121,
      isOpenNow: true,
      verified: true,
      phone: "+919122334455",
      whatsappNumber: "+919122334455",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "s-5",
      name: "Prerna Coaching Classes",
      category: "Education",
      locality: "Civil Lines",
      city: "Prayagraj",
      rating: 4.7,
      reviewCount: 204,
      isOpenNow: false,
      verified: true,
      phone: "+919488001177",
      whatsappNumber: "+919488001177",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "b-4",
      name: "Ganraj Caterers",
      category: "Catering",
      locality: "Shahupuri",
      city: "Kolhapur",
      rating: 4.9,
      reviewCount: 331,
      isOpenNow: true,
      verified: true,
      phone: "+919200334455",
      whatsappNumber: "+919200334455",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "b-5",
      name: "Mehta Auto Garage",
      category: "Auto Services",
      locality: "Navrangpura",
      city: "Ahmedabad",
      rating: 4.4,
      reviewCount: 117,
      isOpenNow: true,
      verified: true,
      phone: "+919355889900",
      whatsappNumber: "+919355889900",
      createdAt: now,
      updatedAt: now,
    },
  ],
  reels: [
    {
      id: "v-101",
      businessId: "b-4",
      vendorName: "Ganraj Caterers",
      handle: "@ganrajcaterers",
      description:
        "Live dosa counter, wedding thali setup, and full-service event staff.",
      city: "Kolhapur",
      verified: true,
      createdAt: now,
    },
    {
      id: "v-102",
      businessId: "b-5",
      vendorName: "Mehta Auto Garage",
      handle: "@mehtaautogarage",
      description:
        "Weekend servicing slots available. Denting, painting, and insurance help.",
      city: "Ahmedabad",
      verified: true,
      createdAt: now,
    },
    {
      id: "v-103",
      businessId: "s-3",
      vendorName: "Morya Paint House",
      handle: "@moryapainthouse",
      description:
        "Compact modular wall-finish bundles for residential and office upgrades.",
      city: "Pune",
      verified: false,
      createdAt: now,
    },
  ],
  offers: [
    {
      id: "o-1",
      title: "Up to 30% Off Home Services",
      subtitle: "Limited time launch discount on selected verified vendors.",
      badge: "Launch Deal",
      active: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "o-2",
      title: "Free Quote on Bulk Orders",
      subtitle: "Manufacturing and logistics suppliers can respond within 15 mins.",
      badge: "B2B",
      active: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "o-3",
      title: "Clinic Booking Week",
      subtitle: "Healthcare listings get priority placement for local patients.",
      badge: "Healthcare",
      active: true,
      createdAt: now,
      updatedAt: now,
    },
  ],
  leads: [],
};
